### ISSUE TITLE
Zeppelin error

### ISSUE THREAD

**Issue by fire** [SnappyDataInc/zeppelin-interpreter#14]
On Snappydata 1.0 and with zeppelin 0.7.2.

Will try zeppelin 0.7.3.

```scala
%snappydata

val data = Array(1, 2, 3, 4, 5)
val distData = sc.parallelize(data)
```
```java
java.lang.NullPointerException
	at org.apache.zeppelin.interpreter.SnappyDataZeppelinInterpreter.open(SnappyDataZeppelinInterpreter.java:506)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:491)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
17/10/09 14:16:39.991 UTC pool-19-thread-34<tid=0xf> ERROR ZeppelinIntpUtil:
  | java.lang.reflect.InvocationTargetException
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.apache.zeppelin.interpreter.ZeppelinIntpUtil.invokeMethod(ZeppelinIntpUtil.java:62)
  | at org.apache.zeppelin.interpreter.SnappyDataZeppelinInterpreter.interpret(SnappyDataZeppelinInterpreter.java:571)
  | at org.apache.zeppelin.interpreter.SnappyDataZeppelinInterpreter.open(SnappyDataZeppelinInterpreter.java:502)
  | at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
  | at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:491)
  | at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
  | at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.NoSuchMethodError: scala.reflect.internal.Symbols$Symbol.hasJavaEnumFlag()Z
  | at scala.tools.nsc.typechecker.Namers$Namer.isEnumConstant(Namers.scala:148)
  | at scala.tools.nsc.typechecker.Namers$Namer.noEnterGetterSetter(Namers.scala:126)
  | at scala.tools.nsc.typechecker.Namers$Namer.enterValDef(Namers.scala:659)
  | at scala.tools.nsc.typechecker.Namers$Namer.dispatch$1(Namers.scala:287)
  | at scala.tools.nsc.typechecker.Namers$Namer.standardEnterSym(Namers.scala:299)
  | at scala.tools.nsc.typechecker.AnalyzerPlugins$class.pluginsEnterSym(AnalyzerPlugins.scala:422)
  | at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.pluginsEnterSym(ReplGlobal.scala:23)
  | at scala.tools.nsc.typechecker.Namers$Namer.enterSym(Namers.scala:275)
  | at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$enterSyms$1.apply(Namers.scala:501)
  | at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$enterSyms$1.apply(Namers.scala:500)
  | at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  | at scala.collection.immutable.List.foldLeft(List.scala:84)
  | at scala.tools.nsc.typechecker.Namers$Namer.enterSyms(Namers.scala:500)
  | at scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:926)
  | at scala.tools.nsc.typechecker.Namers$Namer.classSig(Namers.scala:969)
  | at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1524)
  | at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1542)
  | at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:782)
  | at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:781)
  | at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:781)
  | at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1569)
  | at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:781)
  | at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:773)
  | at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1685)
  | at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1693)
  | at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1683)
  | at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1488)
  | at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1633)
  | at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5008)
  | at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
  | at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
  | at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
  | at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
  | at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
  | at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5452)
  | at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3047)
  | at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
  | at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
  | at scala.collection.immutable.List.loop$1(List.scala:173)
  | at scala.collection.immutable.List.mapConserve(List.scala:189)
  | at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3151)
  | at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5015)
  | at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5312)
  | at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
  | at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
  | at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
  | at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
  | at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
  | at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
  | at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5448)
  | at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
  | at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
  | at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
  | at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
  | at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
  | at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
  | at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  | at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  | at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
  | at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
  | at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
  | at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
  | at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:435)
  | at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:855)
  | at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:813)
  | at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:1002)
  | at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:997)
  | at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:579)
  | at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:567)
  | at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
  | ... 18 more
  | 17/10/09 14:16:39.992 UTC pool-19-thread-34<tid=0xf> ERROR Job: Job failed
  | java.lang.NullPointerException
  | at org.apache.zeppelin.interpreter.SnappyDataZeppelinInterpreter.open(SnappyDataZeppelinInterpreter.java:506)
  | at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
  | at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:491)
  | at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
  | at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | 17/10/09 14:16:39.992 UTC pool-19-thread-34<tid=0xf> INFO SchedulerFactory: Job remoteInterpretJob_1507558599460 finished by scheduler org.apache.zeppelin.interpreter.SnappyDataZeppelinInterpreter50364169
  | 17/10/09 14:16:42.078 UTC pool-19-thread-13<tid=0xf> INFO SchedulerFactory: Job remoteInterpretJob_1507558602078 started by scheduler org.apache.zeppelin.interpreter.SnappyDataSqlZeppelinInterpreter1553789467
  | 17/10/09 14:16:42.100 UTC pool-19-thread-13<tid=0xf> INFO SchedulerFactory: Job remoteInterpretJob_1507558602078 finished by scheduler org.apache.zeppelin.interpreter.SnappyDataSqlZeppelinInterpreter1553789467
```

**Comment by fire** [comment]
Trying solution listed at the bottom of https://issues.apache.org/jira/browse/ZEPPELIN-1511 

> Mina Lee added a comment - 02/Oct/16 06:41
I think there is some conflict between seunjeon_2.11 and Spark interpreter since Spark interpreter includes scala-library and scala-reflection. Work around would be adding org.scala-lang:scala-library,org.scala-lang:scala-reflect to exclude field in GUI

Nevermind this has no relationship.

**Comment by fire** [comment]
Trying shadowjar with .\gradlew publishLocal .

**Comment by sumwale** [comment]
@fire Are you following the steps in https://snappydatainc.github.io/snappydata/howto/use_apache_zeppelin_with_snappydata/

Can you confirm that there are no other conflicting jars in the product jars directory apart from those from the distribution? I just tried with 1.0.0 and zeppelin 0.7.2 netinst package as per above steps and it is working fine for me.
